services:
  nginx:
    image: "nginx:latest"
    ports:
      - "8006:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./:/var/www/laravel    
  php:
    build: 
      context: dockerfiles
      dockerfile: php.Dockerfile
    volumes:
      - ./:/var/www/laravel    
  mysql:
    restart: always
    image: mysql:9.2.0
    ports:
      - "3318:3306"
    env_file:
      - ./env/mysql.env
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - "8007:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: password 
  composer:
    build:
      context: dockerfiles
      dockerfile: composer.Dockerfile
    volumes: 
      - ./:/var/www/laravel
  artisan:
    build:
      context: dockerfiles
      dockerfile: php.Dockerfile    
    volumes:
      - ./:/var/www/laravel
    entrypoint: ["php", "/var/www/laravel/artisan"]    